/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_osdependent_systemtray_appindicator_starcom_NativeAppIndicator */

#ifndef _Included_net_java_sip_communicator_impl_osdependent_systemtray_appindicator_starcom_NativeAppIndicator
#define _Included_net_java_sip_communicator_impl_osdependent_systemtray_appindicator_starcom_NativeAppIndicator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_osdependent_systemtray_appindicator_starcom_NativeAppIndicator
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_osdependent_systemtray_appindicator_starcom_NativeAppIndicator_init
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray, jstring);

/*
 * Class:     net_java_sip_communicator_impl_osdependent_systemtray_appindicator_starcom_NativeAppIndicator
 * Method:    upIcons
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_osdependent_systemtray_appindicator_starcom_NativeAppIndicator_upIcons
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     net_java_sip_communicator_impl_osdependent_systemtray_appindicator_starcom_NativeAppIndicator
 * Method:    quitApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_osdependent_systemtray_appindicator_starcom_NativeAppIndicator_quitApp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
